version: "3.8"
services:
  app:
    container_name: question_app
    build:
      context: .
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PORT: "${POSTGRES_PORT}"
      POSTGRES_HOST: "${POSTGRES_HOST}"
    entrypoint: sh -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0"
    ports:
      - "${APP_PORT}:8000"
    networks:
      - custom
    depends_on:
      db:
        condition: service_healthy
  db:
    container_name: "questionapp-db"
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    networks:
      - custom
    volumes:
      - questionapp-db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "psql -U ${POSTGRES_USER}", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
      interval: 3s
      timeout: 10s
      retries: 10

volumes:
  questionapp-db:

networks:
  custom:
    driver: bridge
